controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    swerve_drive_controller:
      type: swerve_drive_controller/SwerveDriveController

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["left_drive_joint"]
    right_wheel_names: ["right_drive_joint"]

    wheel_separation: 0.93
    wheel_radius: 0.1015

    odom_frame_id: "odom"
    base_frame_id: "base_footprint"

    enable_odom_tf: true   
    enable_odom: true      
    publish_rate: 50.0       
    use_stamped_vel: true     
    cmd_vel_timeout: 0.25     

swerve_drive_controller:
  ros__parameters:
    update_rate: 100

    odom_topic: "/odom"

    odom_frame_id: "odom"
    base_frame_id: "base_footprint"

    smoother:
      max_accel_linear:  1.5    # Normal Velocity m/s²
      max_accel_angular: 3.0    # Normal Angular Velocity rad/s²
      max_decel_linear:  4.0    # Emergency Decel m/s²
      max_decel_angular: 6.0    # Emergency Angular Decel rad/s²
      stop_threshold_linear:  0.01
      stop_threshold_angular: 0.01

    cmd_vel_limit:
      vx_limit: [-1.0, 1.0]  # m/s
      vy_limit: [-0.8, 0.8]  # m/s
      wz_limit: [-1.5, 1.5]  # rad/s

    steer_joint_names:
      - "front_steer_joint"
      - "left_steer_joint"
      - "right_steer_joint"  

    drive_joint_names:
      - "front_drive_joint"
      - "left_drive_joint"
      - "right_drive_joint"

    state_interface_names:
      - "position"
      - "velocity"
    
    wheel_radius: 0.1015

    # Positions of wheels relative to robot center of mass
    wheel_to_center:
      front: 0.6096   # m
      left: 0.6096    # m
      right: 0.6096   # m


    # Assuming the vehicle body coordinate system is placed at the center of the robot, 
    # and the wheels are located at 120 degree intervals around the center.
    alpha:
      front: 0.0
      left: 2.0944    # 120 degrees in radians
      right: 4.1888   # 240 degrees in radians