<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>warrior_bringup</name>
  <version>0.0.0</version>
  <description>The bringup package for the Warrior robot</description>
  <maintainer email="yihaocai007@gmail.com">Yihao Cai</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>warrior_description</depend>
  <depend>warrior_control</depend>
  <depend>warrior_driver</depend>
  <depend>warrior_gazebo</depend>
  <depend>warrior_system</depend>
  <depend>robot_state_publisher</depend>
  <depend>joint_state_publisher</depend>
  <depend>controller_manager</depend>
  <depend>diff_drive_controller</depend>
  <depend>rviz2</depend>
  <depend>warrior_joy</depend>
  <depend>warrior_serial</depend>
  <depend>warrior_msgs</depend>
  <depend>warrior_localization</depend>
  <depend>warrior_navigation</depend>
  <depend>gps_localization</depend>
  <!-- <depend>omnivision</depend> -->
  <depend>joy</depend>
  <exec_depend>teleop_twist_joy</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
