unitree_lidar_ros2_node:
  ros__parameters:
    use_udp: true
    initialize_type: 2
    work_mode: 0
    use_system_timestamp: true
    range_min: 0.0
    range_max: 100.0
    cloud_scan_num: 18

    # Ethernet. This LiDAR was reconfigured to 192.168.123.110.
    lidar_ip: "192.168.1.62"
    lidar_port: 6101
    local_ip: "192.168.1.2"
    local_port: 6201

    serial_port: "/dev/ttyACM0"
    baudrate: 4000000

    cloud_frame: "unilidar_lidar"
    cloud_topic: "unilidar/cloud"
    imu_frame: "unilidar_imu"
    imu_topic: "unilidar/imu"
