multitask_node:
  ros__parameters:
    image_topic:       camera/image_raw
    seg_topic:         ai/seg_mask
    detections_topic:  ai/detections
    score_threshold:   0.20
    nms_threshold:     0.50
    apply_morph:       false
