# cares_gps_config.yaml
gps_localization:
  apriltag_gps_bridge:
    ros__parameters:
      robot_name: mini_shanti
      camera_parameters: [514.8914923, 515.01073552, 320.13602236,]
      
  world_gps_node:
    ros__parameters:
      use_hardware_gps: false  # Always false for indoor
      fixed_latitude: 42.3558128
      fixed_longitude:  -83.0707164
      fixed_altitude: 200.0
      
  waypoint_navigator:
    ros__parameters:
      robot_name: mini_shanti
      utm_zone: 17
      waypoint_tolerance: 0.3

      
      # CARES LAB WAYPOINTS
      waypoint_1_lat: 42.3558186
      waypoint_1_lon: -83.0707180
      waypoint_2_lat: 42.35581677
      waypoint_2_lon: -83.070701
      waypoint_3_lat: 42.3558071
      waypoint_3_lon: -83.0707157
      waypoint_4_lat: 42.3558072
      waypoint_4_lon: -83.070723

      
  robot_frame_node:
    ros__parameters:
      robot_name: mini_shanti
      initial_x: 0.0
      initial_y: 0.0
      initial_z: 0.0
